# Code accompanying the article: "Genetic Risk of Type 2 Diabetes and Dementia: A Polygenic Risk Score and Cluster-Based Analysis in the KARE Study"
# Written by Zhou Lab, 2025.06
# For illustrative purposes – not optimized for production use.

#### environment ####
library(tidyverse)
library(survival)  
library(cmprsk)
library(xlsx)
# dummy data generated by synthpop
dummy_df <- readRDS("./dummy_df.rds")

#### results: Association between T2D PRS and Dementia ####
res <- NULL
for (outcome in c("痴呆", "阿尔兹海默", "VD", "other痴呆")) {
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(T2D_index_snps_PRS) + AGE_ON_CUTOFF + SEX + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df)
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    res1 <- data.frame(HR_unadjusted = hr_ci, p_unadjusted = p)
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(T2D_index_snps_PRS) + AGE_ON_CUTOFF + SEX + group + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df)
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    res2 <- data.frame(HR_adjusted = hr_ci, p_adjusted = p)
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(T2D_index_snps_PRS) + AGE_ON_CUTOFF + SEX + group + PC1 + PC2 + PC3 + PC4 + PC5 + as.factor(学历编码) + as.factor(婚姻编码) + as.factor(农村和城镇) + as.factor(吸烟状况编码) + as.factor(饮酒频率编码) + 低密度脂蛋白 + 高密度脂蛋白 + 总胆固醇 + 甘油三酯_x + 右侧收缩压 + 右侧舒张压 + BMI + 空腹血糖 + as.factor(脑血管病) + as.factor(缺血性心脏病) + as.factor(心力衰竭) + as.factor(睡眠障碍) + as.factor(抑郁)")), data = dummy_df)
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    res3 <- data.frame(HR_adjusted2 = hr_ci, p_adjusted2 = p)
    
    res <- rbind(res, 
                 cbind(data.frame(Disease = outcome), res1, res2, res3))
}
t2 <- res
# ph tests for primary results
cox_model <- coxph(Surv(time = 随访年数_VD, event = VD) ~ T2D_index_snps_PRS + AGE_ON_CUTOFF + SEX + group, data = dummy_df)
ph_test <- cox.zph(cox_model)
print(ph_test)
plot(ph_test)

#### results: Association between partitioned T2D PRS and incident Vascular Dementia ####
prs_columns <- c("ALPNeg_PRS", "beta_cell1_PRS", "beta_cell2_PRS", 
                 "Bilirubin_PRS", "cholesterol_PRS", "hyperInsulin_PRS", 
                 "lipodystrophy1_PRS", "lipodystrophy2_PRS", "liverLipid_PRS",
                 "obesity_PRS_x", "proinsulin_PRS", "SHBGLpA_PRS")
results <- NULL
for (prs in prs_columns) {
    res <- NULL
    for (outcome in c("VD")) {
        
        cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(", prs, ") + AGE_ON_CUTOFF + SEX + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df)
        summary_model <- summary(cox_model)
        hr <- summary_model$coefficients[1, "exp(coef)"]
        ci_lower <- summary_model$conf.int[1, "lower .95"]
        ci_upper <- summary_model$conf.int[1, "upper .95"]
        p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
        hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
        p <- sprintf('%.3f', p_val)
        if (p == "0.000") p <- "<0.001"
        res1 <- data.frame(HR_unadjusted = hr_ci, p_unadjusted = p)
        
        cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(", prs, ") + AGE_ON_CUTOFF + SEX + group + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df)
        summary_model <- summary(cox_model)
        hr <- summary_model$coefficients[1, "exp(coef)"]
        ci_lower <- summary_model$conf.int[1, "lower .95"]
        ci_upper <- summary_model$conf.int[1, "upper .95"]
        p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
        hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
        p <- sprintf('%.3f', p_val)
        if (p == "0.000") p <- "<0.001"
        res2 <- data.frame(HR_adjusted = hr_ci, p_adjusted = p)
        
        cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(", prs, ") + AGE_ON_CUTOFF + SEX + group + PC1 + PC2 + PC3 + PC4 + PC5 + as.factor(学历编码) + as.factor(婚姻编码) + as.factor(农村和城镇) + as.factor(吸烟状况编码) + as.factor(饮酒频率编码) + 低密度脂蛋白 + 高密度脂蛋白 + 总胆固醇 + 甘油三酯_x + 右侧收缩压 + 右侧舒张压 + BMI + 空腹血糖 + as.factor(脑血管病) + as.factor(缺血性心脏病) + as.factor(心力衰竭) + as.factor(睡眠障碍) + as.factor(抑郁)")), data = dummy_df)
        summary_model <- summary(cox_model)
        hr <- summary_model$coefficients[1, "exp(coef)"]
        ci_lower <- summary_model$conf.int[1, "lower .95"]
        ci_upper <- summary_model$conf.int[1, "upper .95"]
        p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
        hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
        p <- sprintf('%.3f', p_val)
        if (p == "0.000") p <- "<0.001"
        res3 <- data.frame(HR_adjusted2 = hr_ci, p_adjusted2 = p)
        
        res <- rbind(res, 
                     cbind(data.frame(pPS = prs), res1, res2, res3))
    }
    results <- rbind(results, res)
}
t3 <- results
# ph tests for primary results
cox_model <- coxph(Surv(time = 随访年数_VD, event = VD) ~ hyperInsulin_PRS + AGE_ON_CUTOFF + SEX + group, data = dummy_df)
ph_test <- cox.zph(cox_model)
print(ph_test)
plot(ph_test)
cox_model <- coxph(Surv(time = 随访年数_VD, event = VD) ~ SHBGLpA_PRS + AGE_ON_CUTOFF + SEX + group, data = dummy_df)
ph_test <- cox.zph(cox_model)
print(ph_test)
plot(ph_test)

# categorical
prs_columns <- c("hyperInsulin_PRS_三分位", "SHBGLpA_PRS_三分位")
prs_colnames <- data.frame(PRS = c("hyperInsulin_low_pps", "hyperInsulin_med_pps", "hyperInsulin_high_pps", "SHBGLpA_low_pps", "SHBGLpA_med_pps", "SHBGLpA_high_pps"))
results <- NULL
for (prs in prs_columns) {
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ as.factor(", prs, ") + AGE_ON_CUTOFF + SEX + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df)
    
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    
    res11 <- data.frame(HR_unadjusted = hr_ci, p_unadjusted = p)
    
    hr <- summary_model$coefficients[2, "exp(coef)"]
    ci_lower <- summary_model$conf.int[2, "lower .95"]
    ci_upper <- summary_model$conf.int[2, "upper .95"]
    p_val <- summary_model$coefficients[2, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    
    res12 <- data.frame(HR_unadjusted = hr_ci, p_unadjusted = p)
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ as.factor(", prs, ") + AGE_ON_CUTOFF + SEX + group + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df)
    
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    
    res21 <- data.frame(HR_adjusted = hr_ci, p_adjusted = p)
    
    hr <- summary_model$coefficients[2, "exp(coef)"]
    ci_lower <- summary_model$conf.int[2, "lower .95"]
    ci_upper <- summary_model$conf.int[2, "upper .95"]
    p_val <- summary_model$coefficients[2, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    
    res22 <- data.frame(HR_adjusted = hr_ci, p_adjusted = p)
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ as.factor(", prs, ") + AGE_ON_CUTOFF + SEX + group + PC1 + PC2 + PC3 + PC4 + PC5 + as.factor(学历编码) + as.factor(婚姻编码) + as.factor(农村和城镇) + as.factor(吸烟状况编码) + as.factor(饮酒频率编码) + 低密度脂蛋白 + 高密度脂蛋白 + 总胆固醇 + 甘油三酯_x + 右侧收缩压 + 右侧舒张压 + BMI + 空腹血糖 + as.factor(脑血管病) + as.factor(缺血性心脏病) + as.factor(心力衰竭) + as.factor(睡眠障碍) + as.factor(抑郁)")), data = dummy_df)
    
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    
    res31 <- data.frame(HR_adjusted2 = hr_ci, p_adjusted2 = p)
    
    hr <- summary_model$coefficients[2, "exp(coef)"]
    ci_lower <- summary_model$conf.int[2, "lower .95"]
    ci_upper <- summary_model$conf.int[2, "upper .95"]
    p_val <- summary_model$coefficients[2, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    
    res32 <- data.frame(HR_adjusted2 = hr_ci, p_adjusted2 = p)
    
    results <- rbind(results,
                     rbind(data.frame(HR_unadjusted = "(Ref)", p_unadjusted = "", HR_adjusted = "(Ref)", p_adjusted = "", HR_adjusted2 = "(Ref)", p_adjusted2 = ""),
                           cbind(res11, res21, res31),
                           cbind(res12, res22, res32)))
}
results <- cbind(prs_colnames, results)
st5 <- results

#### Sensitivity analysis ####
# PRS excluding APOE variants
res <- NULL
for (outcome in c("痴呆", "阿尔兹海默", "VD", "other痴呆")) {
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(T2D_index_prs_remove) + AGE_ON_CUTOFF + SEX + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df)
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    res1 <- data.frame(HR_unadjusted = hr_ci, p_unadjusted = p)
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(T2D_index_prs_remove) + AGE_ON_CUTOFF + SEX + group + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df)
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    res2 <- data.frame(HR_adjusted = hr_ci, p_adjusted = p)
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(T2D_index_prs_remove) + AGE_ON_CUTOFF + SEX + group + PC1 + PC2 + PC3 + PC4 + PC5 + as.factor(学历编码) + as.factor(婚姻编码) + as.factor(农村和城镇) + as.factor(吸烟状况编码) + as.factor(饮酒频率编码) + 低密度脂蛋白 + 高密度脂蛋白 + 总胆固醇 + 甘油三酯_x + 右侧收缩压 + 右侧舒张压 + BMI + 空腹血糖 + as.factor(脑血管病) + as.factor(缺血性心脏病) + as.factor(心力衰竭) + as.factor(睡眠障碍) + as.factor(抑郁)")), data = dummy_df)
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    res3 <- data.frame(HR_adjusted2 = hr_ci, p_adjusted2 = p)
    
    res <- rbind(res, 
                 cbind(data.frame(Disease = outcome), res1, res2, res3))
}
st8 <- res

# Sex stratification
data_ori_male <- filter(dummy_df, SEX == 1)
data_ori_female <- filter(dummy_df, SEX == 2)
res <- NULL
for (outcome in c("VD")) {
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(T2D_index_snps_PRS) + AGE_ON_CUTOFF + SEX + PC1 + PC2 + PC3 + PC4 + PC5")), data = data_ori_male)
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    res1 <- data.frame(HR = hr_ci, p = p)
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(T2D_index_snps_PRS) + AGE_ON_CUTOFF + SEX + group + PC1 + PC2 + PC3 + PC4 + PC5")), data = data_ori_male)
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    res2 <- data.frame(HR = hr_ci, p = p)
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(T2D_index_snps_PRS) + AGE_ON_CUTOFF + SEX + group + PC1 + PC2 + PC3 + PC4 + PC5 + as.factor(学历编码) + as.factor(婚姻编码) + as.factor(农村和城镇) + as.factor(吸烟状况编码) + as.factor(饮酒频率编码) + 低密度脂蛋白 + 高密度脂蛋白 + 总胆固醇 + 甘油三酯_x + 右侧收缩压 + 右侧舒张压 + BMI + 空腹血糖 + as.factor(脑血管病) + as.factor(缺血性心脏病) + as.factor(心力衰竭) + as.factor(睡眠障碍) + as.factor(抑郁)")), data = data_ori_male)
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    res3 <- data.frame(HR = hr_ci, p = p)
    
    res <- rbind(res1, res2, res3)
}
res_male <- res
res <- NULL
for (outcome in c("VD")) {
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(T2D_index_snps_PRS) + AGE_ON_CUTOFF + PC1 + PC2 + PC3 + PC4 + PC5")), data = data_ori_female)
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    res1 <- data.frame(HR = hr_ci, p = p)
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(T2D_index_snps_PRS) + AGE_ON_CUTOFF + group + PC1 + PC2 + PC3 + PC4 + PC5")), data = data_ori_female)
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    res2 <- data.frame(HR = hr_ci, p = p)
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(T2D_index_snps_PRS) + AGE_ON_CUTOFF + SEX + group + PC1 + PC2 + PC3 + PC4 + PC5 + as.factor(学历编码) + as.factor(婚姻编码) + as.factor(农村和城镇) + as.factor(吸烟状况编码) + as.factor(饮酒频率编码) + 低密度脂蛋白 + 高密度脂蛋白 + 总胆固醇 + 甘油三酯_x + 右侧收缩压 + 右侧舒张压 + BMI + 空腹血糖 + as.factor(脑血管病) + as.factor(缺血性心脏病) + as.factor(心力衰竭) + as.factor(睡眠障碍) + as.factor(抑郁)")), data = data_ori_female)
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    res3 <- data.frame(HR = hr_ci, p = p)
    
    res <- rbind(res1, res2, res3)
}
temp_res <- cbind(data.frame(Model = paste0("Model ", seq_len(3))), res_male, res)
colnames(temp_res)[2:5] <- c("HR_male", "p_male", "HR_female", "p_female")
res <- NULL
for (outcome in c("VD")) {
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(T2D_index_snps_PRS) * as.factor(SEX) + AGE_ON_CUTOFF + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df)
    summary_model <- summary(cox_model)
    p <- summary_model$coefficients["scale(T2D_index_snps_PRS):as.factor(SEX)2", "Pr(>|z|)"]
    p <- sprintf('%.3f', p)
    if (p == "0.000") p <- "<0.001"
    res1 <- data.frame(p_for_interaction = p)
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(T2D_index_snps_PRS) * as.factor(SEX) + AGE_ON_CUTOFF + group + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df)
    summary_model <- summary(cox_model)
    p <- summary_model$coefficients["scale(T2D_index_snps_PRS):as.factor(SEX)2", "Pr(>|z|)"]
    p <- sprintf('%.3f', p)
    if (p == "0.000") p <- "<0.001"
    res2 <- data.frame(p_for_interaction = p)
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(T2D_index_snps_PRS) * as.factor(SEX) + AGE_ON_CUTOFF + group + PC1 + PC2 + PC3 + PC4 + PC5 + as.factor(学历编码) + as.factor(婚姻编码) + as.factor(农村和城镇) + as.factor(吸烟状况编码) + as.factor(饮酒频率编码) + 低密度脂蛋白 + 高密度脂蛋白 + 总胆固醇 + 甘油三酯_x + 右侧收缩压 + 右侧舒张压 + BMI + 空腹血糖 + as.factor(脑血管病) + as.factor(缺血性心脏病) + as.factor(心力衰竭) + as.factor(睡眠障碍) + as.factor(抑郁)")), data = dummy_df)
    summary_model <- summary(cox_model)
    p <- summary_model$coefficients["scale(T2D_index_snps_PRS):as.factor(SEX)2", "Pr(>|z|)"]
    p <- sprintf('%.3f', p)
    if (p == "0.000") p <- "<0.001"
    res3 <- data.frame(p_for_interaction = p)
    
    res <- rbind(res1, res2, res3)
}
temp_res <- cbind(temp_res, res)
st9 <- temp_res

prs_columns <- c("hyperInsulin_PRS", "SHBGLpA_PRS")
results <- NULL
for (prs in prs_columns) {
    res <- NULL
    for (outcome in c("VD")) {
        cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(", prs, ") + AGE_ON_CUTOFF + PC1 + PC2 + PC3 + PC4 + PC5")), data = data_ori_male)
        summary_model <- summary(cox_model)
        hr <- summary_model$coefficients[1, "exp(coef)"]
        ci_lower <- summary_model$conf.int[1, "lower .95"]
        ci_upper <- summary_model$conf.int[1, "upper .95"]
        p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
        hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
        p <- sprintf('%.3f', p_val)
        if (p == "0.000") p <- "<0.001"
        res1 <- data.frame(HR = hr_ci, p = p)
        
        cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(", prs, ") + AGE_ON_CUTOFF + group + PC1 + PC2 + PC3 + PC4 + PC5")), data = data_ori_male)
        summary_model <- summary(cox_model)
        hr <- summary_model$coefficients[1, "exp(coef)"]
        ci_lower <- summary_model$conf.int[1, "lower .95"]
        ci_upper <- summary_model$conf.int[1, "upper .95"]
        p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
        hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
        p <- sprintf('%.3f', p_val)
        if (p == "0.000") p <- "<0.001"
        res2 <- data.frame(HR = hr_ci, p = p)
        
        cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(", prs, ") + AGE_ON_CUTOFF + group + PC1 + PC2 + PC3 + PC4 + PC5 + as.factor(学历编码) + as.factor(婚姻编码) + as.factor(农村和城镇) + as.factor(吸烟状况编码) + as.factor(饮酒频率编码) + 低密度脂蛋白 + 高密度脂蛋白 + 总胆固醇 + 甘油三酯_x + 右侧收缩压 + 右侧舒张压 + BMI + 空腹血糖 + as.factor(脑血管病) + as.factor(缺血性心脏病) + as.factor(心力衰竭) + as.factor(睡眠障碍) + as.factor(抑郁)")), data = data_ori_male)
        summary_model <- summary(cox_model)
        hr <- summary_model$coefficients[1, "exp(coef)"]
        ci_lower <- summary_model$conf.int[1, "lower .95"]
        ci_upper <- summary_model$conf.int[1, "upper .95"]
        p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
        hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
        p <- sprintf('%.3f', p_val)
        if (p == "0.000") p <- "<0.001"
        res3 <- data.frame(HR = hr_ci, p = p)
        
        res <- rbind(res1, res2, res3)
    }
    results <- rbind(results, res)
}
results_male <- results
prs_columns <- c("hyperInsulin_PRS", "SHBGLpA_PRS")
results <- NULL
for (prs in prs_columns) {
    res <- NULL
    for (outcome in c("VD")) {
        cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(", prs, ") + AGE_ON_CUTOFF + PC1 + PC2 + PC3 + PC4 + PC5")), data = data_ori_female)
        summary_model <- summary(cox_model)
        hr <- summary_model$coefficients[1, "exp(coef)"]
        ci_lower <- summary_model$conf.int[1, "lower .95"]
        ci_upper <- summary_model$conf.int[1, "upper .95"]
        p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
        hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
        p <- sprintf('%.3f', p_val)
        if (p == "0.000") p <- "<0.001"
        res1 <- data.frame(HR = hr_ci, p = p)
        
        cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(", prs, ") + AGE_ON_CUTOFF + group + PC1 + PC2 + PC3 + PC4 + PC5")), data = data_ori_female)
        summary_model <- summary(cox_model)
        hr <- summary_model$coefficients[1, "exp(coef)"]
        ci_lower <- summary_model$conf.int[1, "lower .95"]
        ci_upper <- summary_model$conf.int[1, "upper .95"]
        p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
        hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
        p <- sprintf('%.3f', p_val)
        if (p == "0.000") p <- "<0.001"
        res2 <- data.frame(HR = hr_ci, p = p)
        
        cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(", prs, ") + AGE_ON_CUTOFF + group + PC1 + PC2 + PC3 + PC4 + PC5 + as.factor(学历编码) + as.factor(婚姻编码) + as.factor(农村和城镇) + as.factor(吸烟状况编码) + as.factor(饮酒频率编码) + 低密度脂蛋白 + 高密度脂蛋白 + 总胆固醇 + 甘油三酯_x + 右侧收缩压 + 右侧舒张压 + BMI + 空腹血糖 + as.factor(脑血管病) + as.factor(缺血性心脏病) + as.factor(心力衰竭) + as.factor(睡眠障碍) + as.factor(抑郁)")), data = data_ori_female)
        summary_model <- summary(cox_model)
        hr <- summary_model$coefficients[1, "exp(coef)"]
        ci_lower <- summary_model$conf.int[1, "lower .95"]
        ci_upper <- summary_model$conf.int[1, "upper .95"]
        p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
        hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
        p <- sprintf('%.3f', p_val)
        if (p == "0.000") p <- "<0.001"
        res3 <- data.frame(HR = hr_ci, p = p)
        
        res <- rbind(res1, res2, res3)
    }
    results <- rbind(results, res)
}
temp_res <- cbind(data.frame(pPS = rep(prs_columns, each = 3), Model = rep(paste0("Model ", seq_len(3)), 2)), results_male, results)
colnames(temp_res)[3:6] <- c("HR_male", "p_male", "HR_female", "p_female")
prs_columns <- c("hyperInsulin_PRS", "SHBGLpA_PRS")
results <- NULL
for (prs in prs_columns) {
    res <- NULL
    for (outcome in c("VD")) {
        cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(", prs, ") * as.factor(SEX) + AGE_ON_CUTOFF + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df)
        summary_model <- summary(cox_model)
        p <- summary_model$coefficients[paste0("scale(", prs, "):as.factor(SEX)2"), "Pr(>|z|)"]
        p <- sprintf('%.3f', p)
        if (p == "0.000") p <- "<0.001"
        res1 <- data.frame(p_for_interaction = p)
        
        cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(", prs, ") * as.factor(SEX) + AGE_ON_CUTOFF + group + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df)
        summary_model <- summary(cox_model)
        p <- summary_model$coefficients[paste0("scale(", prs, "):as.factor(SEX)2"), "Pr(>|z|)"]
        p <- sprintf('%.3f', p)
        if (p == "0.000") p <- "<0.001"
        res2 <- data.frame(p_for_interaction = p)
        
        cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ scale(", prs, ") * as.factor(SEX) + AGE_ON_CUTOFF + group + PC1 + PC2 + PC3 + PC4 + PC5 + as.factor(学历编码) + as.factor(婚姻编码) + as.factor(农村和城镇) + as.factor(吸烟状况编码) + as.factor(饮酒频率编码) + 低密度脂蛋白 + 高密度脂蛋白 + 总胆固醇 + 甘油三酯_x + 右侧收缩压 + 右侧舒张压 + BMI + 空腹血糖 + as.factor(脑血管病) + as.factor(缺血性心脏病) + as.factor(心力衰竭) + as.factor(睡眠障碍) + as.factor(抑郁)")), data = dummy_df)
        summary_model <- summary(cox_model)
        p <- summary_model$coefficients[paste0("scale(", prs, "):as.factor(SEX)2"), "Pr(>|z|)"]
        p <- sprintf('%.3f', p)
        if (p == "0.000") p <- "<0.001"
        res3 <- data.frame(p_for_interaction = p)
        
        res <- rbind(res1, res2, res3)
    }
    results <- rbind(results, res)
}
temp_res <- cbind(temp_res, results)
st10 <- temp_res

#### per-variant analysis ####
results <- NULL
outcome <- "VD"
for (snp in c("rs11129735_A", "rs329118_T", "rs858519_分层")) {
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ as.factor(", snp, ") + AGE_ON_CUTOFF + SEX + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df)
    
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    
    res11 <- data.frame(HR_unadjusted = hr_ci, p_unadjusted = p)
    
    hr <- summary_model$coefficients[2, "exp(coef)"]
    ci_lower <- summary_model$conf.int[2, "lower .95"]
    ci_upper <- summary_model$conf.int[2, "upper .95"]
    p_val <- summary_model$coefficients[2, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    
    res12 <- data.frame(HR_unadjusted = hr_ci, p_unadjusted = p)
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ as.factor(", snp, ") + AGE_ON_CUTOFF + SEX + group + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df)
    
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    
    res21 <- data.frame(HR_adjusted = hr_ci, p_adjusted = p)
    
    hr <- summary_model$coefficients[2, "exp(coef)"]
    ci_lower <- summary_model$conf.int[2, "lower .95"]
    ci_upper <- summary_model$conf.int[2, "upper .95"]
    p_val <- summary_model$coefficients[2, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    
    res22 <- data.frame(HR_adjusted = hr_ci, p_adjusted = p)
    
    cox_model <- coxph(as.formula(paste0("Surv(随访年数_", outcome, ", ", outcome, ") ~ as.factor(", snp, ") + AGE_ON_CUTOFF + SEX + group + PC1 + PC2 + PC3 + PC4 + PC5 + as.factor(学历编码) + as.factor(婚姻编码) + as.factor(农村和城镇) + as.factor(吸烟状况编码) + as.factor(饮酒频率编码) + 低密度脂蛋白 + 高密度脂蛋白 + 总胆固醇 + 甘油三酯_x + 右侧收缩压 + 右侧舒张压 + BMI + 空腹血糖 + as.factor(脑血管病) + as.factor(缺血性心脏病) + as.factor(心力衰竭) + as.factor(睡眠障碍) + as.factor(抑郁)")), data = dummy_df)
    
    summary_model <- summary(cox_model)
    hr <- summary_model$coefficients[1, "exp(coef)"]
    ci_lower <- summary_model$conf.int[1, "lower .95"]
    ci_upper <- summary_model$conf.int[1, "upper .95"]
    p_val <- summary_model$coefficients[1, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    
    res31 <- data.frame(HR_adjusted2 = hr_ci, p_adjusted2 = p)
    
    hr <- summary_model$coefficients[2, "exp(coef)"]
    ci_lower <- summary_model$conf.int[2, "lower .95"]
    ci_upper <- summary_model$conf.int[2, "upper .95"]
    p_val <- summary_model$coefficients[2, "Pr(>|z|)"]
    hr_ci <- sprintf('%.3f (%.3f-%.3f)', hr, ci_lower, ci_upper)
    p <- sprintf('%.3f', p_val)
    if (p == "0.000") p <- "<0.001"
    
    res32 <- data.frame(HR_adjusted2 = hr_ci, p_adjusted2 = p)
    
    results <- rbind(results,
                     rbind(data.frame(HR_unadjusted = "(Ref)", p_unadjusted = "", HR_adjusted = "(Ref)", p_adjusted = "", HR_adjusted2 = "(Ref)", p_adjusted2 = ""),
                           cbind(res11, res21, res31),
                           cbind(res12, res22, res32)))
}
t4 <- results

#### T2D ~ pPS ####
prs_columns <- c("ALPNeg_PRS", "beta_cell1_PRS", "beta_cell2_PRS", 
                 "Bilirubin_PRS", "cholesterol_PRS", "hyperInsulin_PRS", 
                 "lipodystrophy1_PRS", "lipodystrophy2_PRS", "liverLipid_PRS",
                 "obesity_PRS_x", "proinsulin_PRS", "SHBGLpA_PRS")
n_pps <- c(6, 76, 34, 2, 4, 39, 44, 26, 6, 72, 15, 3)
results <- data.frame(PRS = prs_columns, N_SNPs = n_pps)
res <- NULL
for (prs in prs_columns) {
    fit <- glm(as.formula(paste0("group ~ scale(", prs, ") + AGE_ON_CUTOFF + SEX + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df, family = binomial())
    or <- sprintf("%0.3f", exp(coef(fit))[2])
    ci <- sprintf("%0.3f", exp(confint(fit))[2, ])
    or_out <- paste0(or, "(", ci[1], "-", ci[2], ")")
    p <- sprintf('%.3f', summary(fit)$coefficients[2, 4])
    if (p == "0.000") p <- "<0.001"
    
    res <- rbind(res, data.frame(OR = or_out,
                                 p_value = p))
}
results <- cbind(results, res)
results$PRS <- gsub("\\_x", "", results$PRS)
results$PRS <- gsub("\\_PRS", "", results$PRS)
colnames(results) <- c("pPS", "N (Variants)", "OR (95% CI)", "p value")
st6 <- results

#### T2D ~ PRS ####
res <- NULL
for (prs in c("T2D_index_snps_PRS", "T2D_index_prs_remove")) {
    fit <- glm(as.formula(paste0("group ~ scale(", prs, ") + AGE_ON_CUTOFF + SEX + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df, family = binomial())
    or <- sprintf("%0.3f", exp(coef(fit))[2])
    ci <- sprintf("%0.3f", exp(confint(fit))[2, ])
    or_out <- paste0(or, " (", ci[1], "-", ci[2], ")")
    p <- sprintf('%.3f', summary(fit)$coefficients[2, 4])
    if (p == "0.000") p <- "<0.001"
    
    res <- rbind(res, data.frame(PRS = prs,
                                 OR = or_out,
                                 p_value = p))
}
print(res)
res <- NULL
for (prs in c("T2D_index_snps_PRS_SAN", "T2D_index_prs_remove_三分位")) {
    fit <- glm(as.formula(paste0("group ~ as.factor(", prs, ") + AGE_ON_CUTOFF + SEX + PC1 + PC2 + PC3 + PC4 + PC5")), data = dummy_df, family = binomial())
    or <- sprintf("%0.3f", exp(coef(fit))[2])
    ci <- sprintf("%0.3f", exp(confint(fit))[2, ])
    or_out <- paste0(or, " (", ci[1], "-", ci[2], ")")
    p <- sprintf('%.3f', summary(fit)$coefficients[2, 4])
    if (p == "0.000") p <- "<0.001"
    
    res <- rbind(res, data.frame(PRS = paste0(prs, "_1"),
                                 OR = or_out,
                                 p_value = p))
    
    or <- sprintf("%0.3f", exp(coef(fit))[3])
    ci <- sprintf("%0.3f", exp(confint(fit))[3, ])
    or_out <- paste0(or, " (", ci[1], "-", ci[2], ")")
    p <- sprintf('%.3f', summary(fit)$coefficients[3, 4])
    if (p == "0.000") p <- "<0.001"
    
    res <- rbind(res, data.frame(PRS = paste0(prs, "_2"),
                                 OR = or_out,
                                 p_value = p))
}
print(res)

#### output ####
output_dir <- "."
write.xlsx(t2,
           paste0("./", output_dir, "/new_tables.xlsx"),
           sheetName = "Table 2",
           append = F,
           row.names = F,
           col.names = T)
write.xlsx(t3,
           paste0("./", output_dir, "/new_tables.xlsx"),
           sheetName = "Table 3",
           append = T,
           row.names = F,
           col.names = T)
write.xlsx(t4,
           paste0("./", output_dir, "/new_tables.xlsx"),
           sheetName = "Table 4",
           append = T,
           row.names = F,
           col.names = T)
for (i_st in c(5, 6, 8, 9, 10)) {
    write.xlsx(get(paste0("st", i_st)),
               paste0("./", output_dir, "/new_tables.xlsx"),
               sheetName = paste0("Supplementary Table ", i_st),
               append = T,
               row.names = F,
               col.names = T)
}
